name: CI/CD UPDATE TRANSLATION

on:
  push:
    branches: 
      - 'translation'

jobs:
  # Perform eslint
  eslint-prettify:
    name: ESlint & Prettify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Run ESLint
      #   uses: stefanoeb/eslint-action@1.0.2
      #   with:
      #     files: -'**/*.json'

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write *.json
  
  # Make a pull request to develop once complete the test
  make-pull-request-on-staging:
    name: Make Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make a pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "" 
          pr_title: "Pulling ${{ github.ref }} into staging" 
          destination_branch: "main" 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "auto-pr, translation"
          pr_reviewer: "farhan-ibrahim"